config/routes.rb
Rails.application.routes.draw do
  resources :ships
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ponto_de_distribuicao.rb
class PontoDeDistribuicao < ApplicationRecord
end

app/models/ship.rb
class Ship < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ponto_distribuicao_controller.rb
class PontoDistribuicaoController < ApplicationController
  require 'rest-client'
  require 'json'

  def index
  	resp = RestClient.get "http://localhost:3005/api/v1/distancias.json"
  	@resposta = JSON.parse(resp.body)  
  end

  def show
  end

  def new
  end

  def create
    @distancia =  params['distancia']
    @origem = params['origem']
    @destino = params['destino']
    resp = RestClient.post "http://localhost:3005/api/v1/distancias.json", {params: {'origem' => @origem, 'destino' => @destino, 'distancia' => @distancia}}
    @url = "http://localhost:3001/ponto_distribuicao/index"
    redirect_to(@url)
  end

  def distancia_params
       params.permit(:distancia, :origem, :destino)  
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  require 'rest-client'
  require 'json'
  before_action :set_ship, only: [:show, :edit, :update, :destroy]



  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
  end

  # GET /ships/new
  def new
   @ships = Ship.new
  end

  # GET /ships/1/edit
  def edit
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ships/1
  # PATCH/PUT /ships/1.json
  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:origem, :destino, :peso)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponto_distribuicao_helper.rb
module PontoDistribuicaoHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioRakuten</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ponto_distribuicao/_form.html.erb
<%= form_for PontoDeDistribuicao.new, method: @method, url: {controller: 'pontoDistribuicao', action: @action} do |f| %>
  <div class="field">
    <%= f.label :origem %>
    <%= f.text_field :origem %>
  </div>
  <div class="field">
    <%= f.label :destino %>
    <%= f.text_field :destino %>
  </div>
  <div class="field">
    <%= f.label :distancia %>
    <%= f.text_field :distancia %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ponto_distribuicao/create.html.erb
<h1>PontoDistribuicao#create</h1>
<p>Find me in app/views/ponto_distribuicao/create.html.erb</p>

app/views/ponto_distribuicao/index.html.erb
<h1>Pontos de Distribuicao</h1>

<table class="table">
	<tr>
		<th>Origem</th>
		<th>Destino</th>
		<th>Distancia</th>
	</tr>
	<% @resposta.each do |ponto| %>
		<tr>
			<td><%= ponto["origem"] %></td>
			<td><%= ponto["destino"] %></td>
			<td><%= ponto["distancia"] %></td>
		</tr>
	<% end %>	
</table>
<%= link_to('Cadastrar Novo',"new") %>

app/views/ponto_distribuicao/new.html.erb
<h1> Cadastar Ponto Distribuicao </h1>

<form role="form" action="#" >
	<div class="form-group">		 
		<label for="origem">
			Origem
		</label>
		<input type="text" class="form-control" id="origem" />
	</div>
	<div class="form-group">		 
		<label for="origem">
			Destino
		</label>
		<input type="text" class="form-control" id="destino" />
	</div>
	<div class="form-group">		 
		<label for="distancia">
			Distancia
		</label>
		<input type="text" class="form-control" id="distancia" />
	</div>
	<button id="salvar" class="btn btn-primary">
		Salvar
	</button>
</form>


<script type="text/javascript">
$("#salvar").click(function(){
  var origem = document.getElementById("origem").value;
  var destino = document.getElementById("destino").value;
  var distancia = document.getElementById("distancia").value;
  $.ajax({
   url : "http://localhost:3005/api/v1/distancias.json",
   type : 'post',
   data : {
            origem,
            destino,
            distancia
           },
    success:function (data) {
    		$(location).attr('href', 'http://localhost:3001/ponto_distribuicao/index');
        }         
	}); 
 
});
</script>

app/views/ponto_distribuicao/show.html.erb
<h1>PontoDistribuicao#show</h1>
<p>Find me in app/views/ponto_distribuicao/show.html.erb</p>

app/views/ships/_form.html.erb
<%= form_with(model: ship, local: true) do |form| %>
    
    <div class="field">
    <%= form.label :peso %>
    <%= form.text_field :peso %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ships/edit.html.erb
<h1>Editing Ship</h1>

<%= render 'form', ship: @ship %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ships</h1>

<table>
  <thead>
    <tr>
      <th>Origem</th>
      <th>Destino</th>
      <th>Peso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ships.each do |ship| %>
      <tr>
        <td><%= ship.origem %></td>
        <td><%= ship.destino %></td>
        <td><%= ship.peso %></td>
        <td><%= link_to 'Show', ship %></td>
        <td><%= link_to 'Edit', edit_ship_path(ship) %></td>
        <td><%= link_to 'Destroy', ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ship', new_ship_path %>

app/views/ships/new.html.erb
<h1>New Ship</h1>


<form role="form" action="#" id="form">
	<div class="form-group">		 
		<label for="origem">
			Origem
		</label>
		<select id="origem">
		  <option value="">Selecione</option>
		</select>
	</div>
	<div class="form-group">		 
		<label for="origem">
			Destino
		</label>
		<select id="destino">
		  <option value="">Selecione</option>
		</select>
	</div>
	<div class="form-group">		 
		<label for="peso">
			Peso
		</label>
		<input type="text" class="form-control" id="peso" />
	</div>
	<button id="calcular" class="btn btn-primary">
		Calcular
	</button>
</form>
<div id="calculo"></div>
<%= link_to 'Voltar', ships_path %>

<script type="text/javascript">
$( document ).ready(function() { 
	$.ajax({
        url: 'http://localhost:3005/api/v1/distancias.json',
        type: 'get',
        success: function(data){
            $.each(data, function(id, obj){
                var option = new Option(obj.origem, obj.origem);
                var optionDestino = new Option(obj.destino, obj.destino);
                $(option).html(obj.origem);
                $(optionDestino).html(obj.destino);
                $("#destino").append(optionDestino);
                $("#origem").append(option);
            });
        }
    });
});
$("#calcular").click(function(){
  var origem = document.getElementById("origem").value;
  var destino = document.getElementById("destino").value;
  var weight = document.getElementById("peso").value;
  $.ajax({
   url : "http://localhost:3006/costs",
   type : 'get',
   data : {
            origem,
            destino,
            weight
           },
    success: function (data) {
    		$("p").remove();
    		var resultado = $("<p></p>").text("O valor do frete é $"+data); 
            $("#calculo").append(resultado);
        }            
	});
});
</script>

app/views/ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origem:</strong>
  <%= @ship.origem %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @ship.destino %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @ship.peso %>
</p>

<%= link_to 'Edit', edit_ship_path(@ship) %> |
<%= link_to 'Back', ships_path %>